defmodule EvoGit.Runtime.PullRequestTest do
  @moduledoc """
  Mutates the process-global `XDG_CONFIG_HOME` env var (read by `EvoGit.Config`) → `async: false`.
  """
  use ExUnit.Case, async: false

  alias EvoGit.Config
  alias EvoGit.Runtime.PullRequest

  # Redirect XDG_CONFIG_HOME to a fresh temp dir (with NO genesis/config.toml) so
  # EvoGit.Config.resolve([:llm, :model]) resolves to nil. This keeps generate_title/2
  # on the pure nil-model path and prevents any accidental real-LLM call if the host
  # machine has a configured model.
  setup do
    original_xdg = System.get_env("XDG_CONFIG_HOME")

    tmp_xdg =
      Path.join(System.tmp_dir!(), "evogit-pr-test-xdg-#{System.unique_integer([:positive])}")

    File.mkdir_p!(tmp_xdg)
    System.put_env("XDG_CONFIG_HOME", tmp_xdg)

    on_exit(fn ->
      if original_xdg do
        System.put_env("XDG_CONFIG_HOME", original_xdg)
      else
        System.delete_env("XDG_CONFIG_HOME")
      end

      File.rm_rf!(tmp_xdg)
    end)

    :ok
  end

  # ==========================================================================
  # format_body/2 — FULLY PURE (no config, no external calls)
  # ==========================================================================
  describe "format_body/2" do
    test "contains the Auto-generated by Genesis header" do
      body = PullRequest.format_body("alice", "All tests passed.")

      assert String.contains?(body, "Auto-generated by Genesis")
    end

    test "contains the github username prefixed with @" do
      body = PullRequest.format_body("alice", "result text")

      assert String.contains?(body, "@alice")
    end

    test "contains the agent result verbatim" do
      body = PullRequest.format_body("alice", "All 42 tests passed.")

      assert String.contains?(body, "All 42 tests passed.")
    end

    test "contains the --- separator on its own line" do
      body = PullRequest.format_body("alice", "result")

      assert String.contains?(body, "\n---\n")
    end

    test "works with empty strings for both arguments" do
      body = PullRequest.format_body("", "")

      # The header is still present
      assert String.contains?(body, "Auto-generated by Genesis")
      # Empty username renders as just the @ with the trailing period
      assert String.contains?(body, "for @.")
      # The Agent Result section is present (with empty content)
      assert String.contains?(body, "## Agent Result")
    end

    test "preserves a multiline agent result verbatim" do
      multiline = """
      Line one of the result.
      Line two of the result.
      Line three of the result.
      """

      body = PullRequest.format_body("bob", multiline)

      assert String.contains?(body, "Line one of the result.")
      assert String.contains?(body, "Line two of the result.")
      assert String.contains?(body, "Line three of the result.")
    end
  end

  # ==========================================================================
  # generate_title/2 — nil-model path only (returns nil without calling the
  # LLM). The non-nil path calls generate_title_with_llm/3 which makes real
  # LLM calls and is intentionally NOT tested here.
  # ==========================================================================
  describe "generate_title/2 (nil-model path)" do
    test "returns nil when no model is configured" do
      # With the isolated (empty) XDG_CONFIG_HOME, no config.toml exists, so
      # Config.resolve([:llm, :model]) is nil.
      assert PullRequest.generate_title("Add login feature", "Done.") == nil
    end

    test "returns nil when the configured model is an empty string" do
      write_empty_model_config()

      assert PullRequest.generate_title("Add login feature", "Done.") == nil
    end
  end

  # Writes a genesis/config.toml into the isolated XDG_CONFIG_HOME with an
  # empty-string model so Config.resolve([:llm, :model]) returns "".
  defp write_empty_model_config do
    dir = Config.config_dir()
    File.mkdir_p!(dir)
    File.write!(Config.config_path(), "[llm]\nmodel = \"\"\n")
  end
end
